"""initial schema

Revision ID: df3ee8018b87
Revises: 
Create Date: 2026-06-21 11:48:55.285304

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df3ee8018b87'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts_account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.Column('avatar', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_staff', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('date_joined', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('name')
    )
    op.create_table('petlisting_pet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_friendly', sa.Boolean(), nullable=False),
    sa.Column('is_adventurous', sa.Boolean(), nullable=False),
    sa.Column('is_extroverted', sa.Boolean(), nullable=False),
    sa.Column('is_introverted', sa.Boolean(), nullable=False),
    sa.Column('is_energetic', sa.Boolean(), nullable=False),
    sa.Column('is_spn', sa.Boolean(), nullable=False),
    sa.Column('is_vaccinated', sa.Boolean(), nullable=False),
    sa.Column('animal_type', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('sex', sa.String(length=20), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('colour', sa.String(length=20), nullable=False),
    sa.Column('breed', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('special_needs', sa.Text(), nullable=True),
    sa.Column('weight', sa.Integer(), nullable=False),
    sa.Column('image1', sa.String(length=255), nullable=False),
    sa.Column('image2', sa.String(length=255), nullable=False),
    sa.Column('image3', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('accounts_seeker',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('city', sa.String(length=255), nullable=True),
    sa.Column('province', sa.String(length=255), nullable=True),
    sa.Column('phone_number', sa.Integer(), nullable=True),
    sa.Column('animal_preference', sa.String(length=255), nullable=True),
    sa.Column('breed_preference', sa.String(length=255), nullable=True),
    sa.Column('age_preference', sa.Integer(), nullable=True),
    sa.Column('sex_preference', sa.String(length=255), nullable=True),
    sa.Column('size_preference', sa.Integer(), nullable=True),
    sa.Column('open_to_special_needs_animals', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts_account.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id')
    )
    op.create_table('accounts_shelter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('city', sa.String(length=255), nullable=False),
    sa.Column('province', sa.String(length=255), nullable=False),
    sa.Column('phone_number', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts_account.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id')
    )
    op.create_table('notification_notification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=200), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('creation_time', sa.DateTime(), nullable=False),
    sa.Column('msg', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['accounts_account.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('blogs_blog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shelter_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=125), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('blog_type', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['shelter_id'], ['accounts_shelter.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comments_review',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('shelter_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(length=500), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('hasReplies', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['accounts_account.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['shelter_id'], ['accounts_shelter.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('petlisting_petlisting',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_posted', sa.DateTime(), nullable=False),
    sa.Column('shelter_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('adoption_fee', sa.Integer(), nullable=False),
    sa.Column('pet_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pet_id'], ['petlisting_pet.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['shelter_id'], ['accounts_shelter.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pet_id')
    )
    op.create_table('applications_application',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('petlisting_id', sa.Integer(), nullable=False),
    sa.Column('seeker_id', sa.Integer(), nullable=True),
    sa.Column('shelter_id', sa.Integer(), nullable=True),
    sa.Column('residence_type', sa.String(length=20), nullable=False),
    sa.Column('fenced_yard', sa.String(length=10), nullable=False),
    sa.Column('pool', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('current_pets', sa.String(length=200), nullable=False),
    sa.Column('address', sa.String(length=50), nullable=False),
    sa.Column('city', sa.String(length=50), nullable=False),
    sa.Column('postal_code', sa.String(length=20), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('other', sa.String(length=50), nullable=True),
    sa.Column('children', sa.String(length=50), nullable=False),
    sa.Column('children_under_13', sa.String(length=50), nullable=False),
    sa.Column('good_fit', sa.Text(), nullable=False),
    sa.Column('schedule', sa.Text(), nullable=False),
    sa.Column('insurance', sa.Text(), nullable=False),
    sa.Column('references', sa.Text(), nullable=False),
    sa.Column('vet', sa.Text(), nullable=False),
    sa.Column('questions', sa.Text(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=False),
    sa.Column('update_time', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['petlisting_id'], ['petlisting_petlisting.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['seeker_id'], ['accounts_seeker.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['shelter_id'], ['accounts_shelter.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('blogs_comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('blog_id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(length=250), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['blog_id'], ['blogs_blog.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['accounts_account.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comments_reply',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('review_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(length=500), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('isSelf', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['accounts_account.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['review_id'], ['comments_review.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comments_message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(length=500), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications_application.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['owner_id'], ['accounts_account.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comments_message')
    op.drop_table('comments_reply')
    op.drop_table('blogs_comment')
    op.drop_table('applications_application')
    op.drop_table('petlisting_petlisting')
    op.drop_table('comments_review')
    op.drop_table('blogs_blog')
    op.drop_table('notification_notification')
    op.drop_table('accounts_shelter')
    op.drop_table('accounts_seeker')
    op.drop_table('petlisting_pet')
    op.drop_table('accounts_account')
    # ### end Alembic commands ###
