# Generated by Django 5.2.11 on 2026-02-19 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_friendly', models.BooleanField(default=False)),
                ('is_adventurous', models.BooleanField(default=False)),
                ('is_extroverted', models.BooleanField(default=False)),
                ('is_introverted', models.BooleanField(default=False)),
                ('is_energetic', models.BooleanField(default=False)),
                ('is_spn', models.BooleanField(default=False)),
                ('is_vaccinated', models.BooleanField(default=False)),
                ('animal_type', models.CharField(choices=[('dog', 'Dog'), ('cat', 'Cat'), ('other', 'Other')], max_length=20)),
                ('name', models.CharField(max_length=40)),
                ('age', models.IntegerField(choices=[(1, 'Infant'), (2, 'Young'), (3, 'Adult'), (4, 'Senior')])),
                ('sex', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=20)),
                ('size', models.IntegerField(choices=[(1, 'Small'), (2, 'Medium'), (3, 'Large')])),
                ('colour', models.CharField(choices=[('black', 'Black'), ('white', 'White'), ('golden', 'Golden')], max_length=20)),
                ('breed', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('special_needs', models.TextField(blank=True, null=True)),
                ('weight', models.PositiveIntegerField()),
                ('image1', models.ImageField(blank=True, default='avatars/default-avatar.jpg', upload_to='avatars/')),
                ('image2', models.ImageField(blank=True, default='avatars/default-avatar.jpg', upload_to='avatars/')),
                ('image3', models.ImageField(blank=True, default='avatars/default-avatar.jpg', upload_to='avatars/')),
            ],
        ),
        migrations.CreateModel(
            name='PetListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('WITHDRAWN', 'Withdrawn'), ('ADOPTED', 'Adopted')], max_length=20)),
                ('adoption_fee', models.PositiveIntegerField()),
                ('pet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='petlisting.pet')),
                ('shelter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.shelter')),
            ],
        ),
    ]
