# Generated by Django 5.2.11 on 2026-02-19 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('residence_type', models.CharField(choices=[('apartment', 'Apartment'), ('condominium', 'Condominium'), ('townhouse', 'Townhouse'), ('house', 'House'), ('other', 'Other')], max_length=20)),
                ('fenced_yard', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=10)),
                ('pool', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('denied', 'Denied'), ('withdrawn', 'Withdrawn')], max_length=20)),
                ('current_pets', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('postal_code', models.CharField(max_length=20)),
                ('phone_number', models.CharField(max_length=20)),
                ('other', models.CharField(blank=True, max_length=50, null=True)),
                ('children', models.CharField(max_length=50)),
                ('children_under_13', models.CharField(max_length=50)),
                ('good_fit', models.TextField()),
                ('schedule', models.TextField()),
                ('insurance', models.TextField()),
                ('references', models.TextField()),
                ('vet', models.TextField()),
                ('questions', models.TextField(blank=True, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
