# Generated by Django 5.2.11 on 2026-02-19 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('applications', '0001_initial'),
        ('petlisting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='petlisting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petlisting.petlisting'),
        ),
        migrations.AddField(
            model_name='application',
            name='seeker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.seeker'),
        ),
        migrations.AddField(
            model_name='application',
            name='shelter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.shelter'),
        ),
    ]
